### ISSUE TITLE
「讨论」关于Rails， Ruby的版本问题

### ISSUE THREAD

**Issue by stardiviner** [LearnRoR-cn/learn-with-project#4]
我们将选择Rails，和Ruby的某一个版本进行开发。这样方便统一。
因为team的repo里需要init一个Rails初始文件。

如果有的人喜欢在4.2，有的喜欢在3.2，那么合并的文件就会有很多问题。
我们会用bundle + rbenv来固定rails和ruby的版本。

**Comment by stardiviner** [comment]
我个人建议使用比较新的Rails 4.2 + Ruby 2.2

**Comment by Matrixbirds** [comment]
of course! 赞同

**Comment by lifesign** [comment]
赞同 :+1:

**Comment by yf0311** [comment]
+1

**Comment by stardiviner** [comment]
Ok, 我会在team repo里推送Rails 4.2，以及Ruby 2.2 产生的Rails初始文件结构。然后推送。
以及在README里添加如何设定的步骤。敬请关注。
