### ISSUE TITLE
[notify] 关于git分支混乱，以及commit提交错误方法。

### ISSUE THREAD

**Issue by stardiviner** [LearnRoR-cn/learn-with-project#6]
@Matrixbirds 我强制修改了team repo的git历史，
这是截图。
![learnror-cn bad git branches](https://cloud.githubusercontent.com/assets/378699/6976963/bf88187c-d9e5-11e4-8948-3fd3aa153394.png)

你能把你的fork删除，然后重新fork么？

**Comment by Matrixbirds** [comment]
ok
